"""Add document-paper association and metadata tracking

Revision ID: 8478ae0841e8
Revises: 4b57f737ecf4
Create Date: 2025-07-16 08:11:41.670834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8478ae0841e8'
down_revision: Union[str, Sequence[str], None] = '4b57f737ecf4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_papers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('paper_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.Column('added_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'paper_id', name='uq_document_paper')
    )
    op.add_column('papers', sa.Column('metadata_source', sa.String(length=50), nullable=True))
    op.add_column('papers', sa.Column('last_metadata_fetch', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('papers', 'last_metadata_fetch')
    op.drop_column('papers', 'metadata_source')
    op.drop_table('document_papers')
    # ### end Alembic commands ###
