"""Add chunk_type, sentence_count, semantic_score and chunk_metadata to paper_chunks

Revision ID: 33509915dce8
Revises: 8478ae0841e8
Create Date: 2025-07-18 15:22:01.016052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33509915dce8'
down_revision: Union[str, Sequence[str], None] = '8478ae0841e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paper_chunks', sa.Column('chunk_type', sa.String(length=50), nullable=True))
    op.add_column('paper_chunks', sa.Column('sentence_count', sa.Integer(), nullable=True))
    op.add_column('paper_chunks', sa.Column('semantic_score', sa.Float(), nullable=True))
    op.add_column('paper_chunks', sa.Column('chunk_metadata', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('paper_chunks', 'chunk_metadata')
    op.drop_column('paper_chunks', 'semantic_score')
    op.drop_column('paper_chunks', 'sentence_count')
    op.drop_column('paper_chunks', 'chunk_type')
    # ### end Alembic commands ###
